[pytest]
minversion = 7.0
addopts = -ra -q
python_files = test_*.py
python_classes = *Test
python_functions = test_*
testpaths = ui_test
pythonpath = ui_test

markers =
    sanity: sanity / functional tests
    smoke: smoke / functional tests
    integration: integration tests
    regression: regression / functional tests
    edge: edge case tests
    e2e: end-to-end (E2E) tests
